### PR TITLE
Update "OBS Mailing list" URL

### PR DESCRIPTION
**Pull request by pyy**

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *openbuildservice* ready!

Built with commit c2a14b10304e57e7323df20ac75474eb9684ece6

https://deploy-preview-291--openbuildservice.netlify.app

**Comment by pyy** [comment]
There are two options:
https://lists.opensuse.org/archives/opensuse-buildservice/
https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/

I don't know use which one actually.

**Comment by dmarcoux** [comment]
Thank you @pyy for submitting this PR.

The link should be https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/. Could you update the PR to reflect this? Thank you :slightly_smiling_face:

**Comment by pyy** [comment]
move to -> #292

**Pull request closed without merging**
