### PR TITLE
Remove superflous author

### PR DESCRIPTION
**Pull request by hennevogel**
Just a netlify example

### CODE REVIEW

**Comment by hennevogel** [comment]
See the deploy status above...

**Comment by mdeniz** [comment]
I see that the screencast videos are not showing in the deploy/netlify... I don't know why

**Comment by Ana06** [comment]
the gems versions are different there, maybe related

**Comment by lethliel** [comment]
The page tries to load scripts from sources that are not trusted. Therefore the screencast is not viewed.

**Comment by hennevogel** [comment]
Yeah the site has to be made protocol proofed :-)

**Pull request closed without merging**
