### PR TITLE
Update books to current state

### PR DESCRIPTION
**Pull request by bgeuken**

### CODE REVIEW

**Comment by hennevogel** [comment]
Deploy preview for *openbuildservice* ready!

Built with commit d6f29b5140571cee12c2a2cc5d466956be275e53

https://deploy-preview-193--openbuildservice.netlify.com

**Comment by dmarcoux** [comment]
A bunch of questions from my naive newcomer point of view.

1. Could we automate this by running the script [update_documentation.sh](https://github.com/openSUSE/obs-landing/blob/master/update_documentation.sh) every X day/week/whenever we need?
2. How often do we need to update the books?

**Comment by hennevogel** [comment]
> Could we automate this by running...
> How often do we need to update...

This should happen as soon as there is a new commit in [openSUSE/obs-docu#master](https://github.com/openSUSE/obs-docu). The "problem" is that this is using [openSUSE/daps](https://github.com/openSUSE/daps) which is not a very popular build tool so it's not easily injected into tools like netlify.

I just added a docker dev-env and travis to obs-docu. Maybe we can get a deploy task going that pushed to master in this repo...

**Comment by bgeuken** [comment]
> dmarcoux commented 3 hours ago
A bunch of questions from my naive newcomer point of view.Could we automate this by running the script update_documentation.sh every X day/week/whenever we need?

We could and we should!
We could have another bot in our [tools repo](https://github.com/openSUSE/obs-tools). Then whenever the master branch of obs-docu changes, our bot would receive a webhook, spins up the docker image, updates the docs and creates a PR.

We just need someone to do it:smile:

> 2. How often do we need to update the books?

Not that often. You could check the PRs to get an idea. AFAIK it's every few month.

**Comment by bgeuken** [comment]
@openSUSE/obs-frontend Please review

**Pull request merged**
