### PR TITLE
Update books to current state

### PR DESCRIPTION
**Pull request by nodeg**
I followed the steps from `obs-docu` and `Updating OBS Documentation` here in the README and used the `update_documentation.sh` to include my changes.
Since there wasn't a recent update here, my commit includes more changes than just the fix I did with https://github.com/openSUSE/obs-docu/pull/186.

### CODE REVIEW

**Review by hennevogel — CHANGES_REQUESTED** [review]
Why are the PDF and epub empty now?

**Comment by hennevogel** [comment]
There is also something wrong with the userguide on the published page

https://deploy-preview-287--openbuildservice.netlify.app/files/manuals/obs-user-guide.epub

**Comment by nodeg** [comment]
That's a good question. In my fork and on my local copy the files are not empty and can be opened and viewed. I an not sure what the `update_documentation.sh` did wrong.

**Comment by hennevogel** [comment]
Let's see :smile_cat:

**Comment by hennevogel** [comment]
This has been done now in https://github.com/openSUSE/obs-landing/commit/4804664062508500985de3d59cf922905fb29224

**Pull request closed without merging**
